layout_spectrum: 0.9477786
typography_spectrum: 0.6599044
color:
  saturation: 0.4497286
  lightness: 0.5452847
  brandStrength: 0.05332007
  rhythmicContrast: 0.4965823
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
name: Whiterectangles
